# Generated by Django 2.2.1 on 2019-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ArtistSingSong',
        ),
    ]
