# Generated by Django 2.2.1 on 2019-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190503_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='introduc',
            field=models.TextField(default='No information'),
        ),
    ]
