# Generated by Django 2.1.7 on 2019-05-13 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190513_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playist',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.RoomListen'),
        ),
    ]
