# Generated by Django 2.2.1 on 2019-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_artist_introduc'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('e', 'EDM'), ('a', 'Acoustic'), ('i', 'Indie'), ('n', 'Nhạc không lời'), ('b', 'Bolero'), ('o', 'other')], default='other', max_length=15),
        ),
    ]
