# Generated by Django 2.2.1 on 2019-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='Nhạc tr', max_length=6),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('n', 'Nhạc trẻ'), ('b', 'Nhạc trữ tình'), ('c', 'Nhạc cách mạng'), ('k', 'Nhạc không lời'), ('q', 'Nhạc quê hương'), ('h', 'Rap/Hip Hop'), ('r', 'Rock Việt'), ('d', 'Dance Việt')], default='other', max_length=15),
        ),
    ]
