# Generated by Django 2.2.1 on 2019-05-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20190503_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSingSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Song')),
            ],
        ),
    ]
