# Generated by Django 2.2.1 on 2019-05-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_artistsingsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='Nhạc trẻ', max_length=6),
        ),
        migrations.AlterField(
            model_name='artistsingsong',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Artist'),
        ),
        migrations.AlterField(
            model_name='artistsingsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Song'),
        ),
    ]
