# Generated by Django 2.2.1 on 2019-05-04 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20190504_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='producer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
