# Generated by Django 2.2.1 on 2019-05-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_artist_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='producer',
        ),
    ]
