# Generated by Django 2.2 on 2019-04-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('introduc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.DurationField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('lyrics', models.TextField()),
                ('audio', models.FileField(upload_to='song/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Artist')),
            ],
        ),
    ]
