# Generated by Django 2.2.1 on 2019-05-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_song_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
